### ISSUE TITLE
Completed module 3 assignments

### ISSUE THREAD

**Issue by coulbyph** [ds4owd-001/md-03-assignments-coulbyph#1]
Hi!
Very interesting module.
I enjoyed it .
Thanks @larnsce @mianzg @sskorik01

**Comment by larnsce** [comment]
Great job, @coulbyph! You can see a comparison of what was deleted/edited (red - left side) and was added (green - right side) here: https://github.com/ds4owd-001/md-03-assignments-coulbyph/commit/467a4d6263c43df99feb745e1bd930f065a4e405

I have added some comments. On each line, one can add comments. A bit like you would do in MS Word with comments and track changes.

I will close the issue for you now.
